table dIconesProdutos
	lineageTag: 34ad86f5-9706-4417-a1d8-71757fcc23c0

	column Categoria
		dataType: string
		lineageTag: 900eaa5f-5cf0-41f3-9e3f-65be77d3a06f
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column 'Icone URL'
		dataType: string
		lineageTag: 642f2d8b-b8ec-4402-b174-1950d66c9f0b
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Icone URL

		annotation SummarizationSetBy = Automatic

	partition dIconesProdutos-e1bbb06c-614b-43e8-aa9e-b50743bd516c = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("dZBBT4MwFID/StMz8nTZNPG2zcCiq/HQMDOyQ1caWqG0QsHor5eB6S71/L7vey8vz/G6L5TBEZbO2e4RQMXqfI65AUoXD8dyD+wCxLYp8SnKMc0QawqUqUIErUO6eDtuKnCDV7ZG296JtgvxpNGr7OcJ+B90tZgWLeumbZxpbtrinwT9TKrkjgKfjGtA1DWy0jQiaH1kpJS378BHbKK8SPpO8QgRMygx759+hDbGVMHUy1ciq90S9EX0mXQ8Z9ap+Q56Olm+Pg8puHHutZ3RAq2trRVrePj0LRn2h/sVyBG9YR6dE6df", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ProductCategoryName = _t, #"Icone URL" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ProductCategoryName", type text}, {"Icone URL", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"ProductCategoryName", "Categoria"}})
				in
				    #"Renamed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

